import Head from "next/head";
import Navbar from "../components/Navbar/Navbar";

import { createTheme, ThemeProvider } from "@mui/material/styles";
import { Box } from "@mui/system";
import { Typography } from "@mui/material";
import Paper from "@mui/material/Paper";
import { Grid } from "@mui/material";
import Fab from "@mui/material/Fab";
import AddIcon from "@mui/icons-material/Add";
import EditIcon from "@mui/icons-material/Edit";
import FavoriteIcon from "@mui/icons-material/Favorite";
import NavigationIcon from "@mui/icons-material/Navigation";

let theme = createTheme({
  palette: {
    mode: "light",
    primary: {
      main: "#fff",
      dark: "#b2b2b2",
    },
    text: {
      primary: "#fff",
    },
  },
});

theme.typography.h1 = {
  "@media (max-width:2000px)": {
    fontSize: "8rem",
  },
  "@media (max-width:1200px)": {
    fontSize: "8rem",
  },
  "@media (max-width:766px)": {
    fontSize: "5rem",
  },
  "@media (max-height:766px)": {
    fontSize: "5rem",
  },

  // [theme.breakpoints.down("xs")]: {
  //   fontSize: "100px",
  // },
};

function Home(props) {
  return (
    <ThemeProvider theme={theme}>
      <div>
        <Head>
          <title> Survey Sparrow Task</title>
          <meta name="description" content="Generated by create next app" />
        </Head>

        {/*---------------------------------------  */}
        <main>
          <Grid
            container
            sx={{
              position: "sticky",
              background: "url('/images/Banner.png')",
              height: "100vh",
              backgroundRepeat: "no-repeat",
              zIndex: "-10",
              backgroundPosition: "center center",
              backgroundSize: "cover",
            }}
          ></Grid>
          <Grid
            sx={{
              position: "sticky",
              mt: "-100vh",
              zIndex: "10rem",
            }}
          >
            <Navbar />
          </Grid>
          <Grid
            sx={{
              position: "absolute",
              bottom: "5vh",
              right: "5vw",
              zIndex: "10rem",
            }}
          >
            <Fab color="primary" aria-label="add">
              <AddIcon />
            </Fab>
          </Grid>
          <Box
            sx={{
              top: "7rem",
              display: "flex",
              position: "absolute",
              marginLeft: "10vh",
              maxWidth: "100vh",
            }}
          >
            <Box md={5} xs={3} lg={5}>
              <Typography
                variant="h1"
                sx={{
                  maxWidth: "40%",
                  color: "primary.main",
                  justifySelf: "flex-start",
                }}
              >
                where words fail, music speaks
              </Typography>
            </Box>
          </Box>
        </main>
      </div>
    </ThemeProvider>
  );
}

export default Home;
