import Head from "next/head";
import Navbar from "../components/Navbar/Navbar";
import Chats from "../components/Chats/Chats";

import { createTheme, ThemeProvider } from "@mui/material/styles";
import { Box } from "@mui/system";
import { Typography } from "@mui/material";
import Paper from "@mui/material/Paper";
import { Grid } from "@mui/material";
import { Container } from "@mui/material";
import Fab from "@mui/material/Fab";
import AddIcon from "@mui/icons-material/Add";
import EditIcon from "@mui/icons-material/Edit";
import FavoriteIcon from "@mui/icons-material/Favorite";
import NavigationIcon from "@mui/icons-material/Navigation";
import Grow from "@mui/material/Grow";
import Collapse from "@mui/material/Collapse";
import CloseIcon from "@mui/icons-material/Close";
import { useState } from "react";

let theme = createTheme({
  palette: {
    mode: "light",
    primary: {
      main: "#fff",
      dark: "#b2b2b2",
      lightBlue: "#7F8AC5",
      blue: "#4C5AA1",
    },
    text: {
      primary: "#fff",
    },
  },
});

theme.typography.h1 = {
  "@media (max-width:2000px)": {
    fontSize: "8rem",
  },
  "@media (max-width:1200px)": {
    fontSize: "8rem",
  },
  "@media (max-width:766px)": {
    fontSize: "5rem",
  },
  "@media (max-height:766px)": {
    fontSize: "5rem",
  },

  // [theme.breakpoints.down("xs")]: {
  //   fontSize: "100px",
  // },
};

function Home(props) {
  let [chatBoxState, changeStateChatBox] = useState(false);
  let [conversationStarted, changeStateConversation] = useState(false);

  return (
    <ThemeProvider theme={theme}>
      <div>
        <Head>
          <title> Survey Sparrow Task</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="preconnect" href="https://fonts.googleapis.com"></link>
          <link
            rel="preconnect"
            href="https://fonts.gstatic.com"
            crossorigin
          ></link>
          <link
            href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300&display=swap"
            rel="stylesheet"
          ></link>
        </Head>

        {/*---------------------------------------  */}
        <main>
          <Grid
            container
            sx={{
              position: "sticky",
              background: "url('/images/Banner.png')",
              height: "100vh",
              backgroundRepeat: "no-repeat",
              zIndex: "-10",
              backgroundPosition: "center center",
              backgroundSize: "cover",
            }}
          ></Grid>
          <Grid
            sx={{
              position: "sticky",
              mt: "-100vh",
              zIndex: "10rem",
            }}
          >
            <Navbar />
          </Grid>
          <Grow
            in={chatBoxState}
            style={{ transformOrigin: "0 0 0" }}
            {...(chatBoxState ? { timeout: 1000 } : {})}
          >
            <Grid
              sx={{
                position: "fixed",
                bottom: "5vh",
                right: "5vw",
                zIndex: "10rem",
              }}
            >
              <Fab
                color="primary"
                aria-label="add"
                onClick={() => {
                  changeStateChatBox(false);
                }}
              >
                {/* <img
                  src="./icons/SparrowBird.png"
                  height="30px"
                  width="auto"
                ></img> */}
                <CloseIcon />
              </Fab>
            </Grid>
          </Grow>

          <Grow
            in={!chatBoxState}
            style={{ transformOrigin: "0 0 0" }}
            {...(chatBoxState ? { timeout: 1000 } : {})}
          >
            <Grid
              sx={{
                position: "fixed",
                bottom: "5vh",
                right: "5vw",
                zIndex: "10rem",
              }}
            >
              <Fab
                color="primary"
                aria-label="add"
                onClick={() => {
                  changeStateChatBox(true);
                }}
              >
                <img
                  src="./icons/SparrowBird.png"
                  height="30px"
                  width="auto"
                ></img>
              </Fab>
            </Grid>
          </Grow>

          <Grow
            in={chatBoxState}
            style={{ transformOrigin: "0 0 50%" }}
            {...(chatBoxState ? { timeout: 1000 } : {})}
          >
            <Box
              className="chats-container-top"
              sx={{
                position: "fixed",
                bottom: "15vh",
                right: "5vw",
                zIndex: "50",
                width: "400px",
              }}
            >
              <Grid sx={{ bgcolor: "primary.main", borderRadius: "5px" }} p={1}>
                <Chats />
              </Grid>
            </Box>
          </Grow>
          <Box
            sx={{
              top: "7rem",
              display: "flex",
              position: "absolute",
              marginLeft: "10vh",
              maxWidth: "100vh",
              zIndex: "-1",
            }}
          >
            <Box md={5} xs={3} lg={5}>
              <Typography
                variant="h1"
                sx={{
                  maxWidth: "40%",
                  color: "primary.main",
                  justifySelf: "flex-start",
                }}
              >
                where words fail, music speaks
              </Typography>
            </Box>
          </Box>
        </main>
      </div>
    </ThemeProvider>
  );
}

export default Home;
