import Head from "next/head";
import Navbar from "../components/Navbar/Navbar";

import { createTheme, ThemeProvider } from "@mui/material/styles";
import { Box } from "@mui/system";
import { Typography } from "@mui/material";
import Paper from "@mui/material/Paper";
import { Grid } from "@mui/material";

let theme = createTheme({
  palette: {
    mode: "light",
    primary: {
      main: "#fff",
      dark: "#b2b2b2",
    },
    text: {
      primary: "#fff",
    },
  },
});

export default function Home() {
  return (
    <ThemeProvider theme={theme}>
      <div>
        <Head>
          <title> Survey Sparrow Task</title>
          <meta name="description" content="Generated by create next app" />
        </Head>

        {/*---------------------------------------  */}
        <main>
          <Grid
            container
            sx={{
              position: "sticky",
              background: "url('/images/Banner.png')",
              height: "100vh",
              backgroundRepeat: "no-repeat",
              zIndex: "-10",
              backgroundPosition: "center center",
              backgroundSize: "cover",
            }}
          ></Grid>
          <Grid
            sx={{
              position: "sticky",
              mt: "-100vh",
              zIndex: "10rem",
            }}
          >
            <Navbar />
          </Grid>
        </main>
      </div>
    </ThemeProvider>
  );
}
